---
title: "flumodelr: Introduction"
author: "Kevin W. McConeghy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flumodelr: 01-Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Welcome to flumodelr! This program was written as a companion to academic work performed by researchers at Brown University in collaboration with Sanofi-Pasteur. The primary objective was to streamline and formalize published work on estimating attributable influenza cases. We drew from many sources which are acknowledged and cited throughout in the development of this package. 

## Introduction

This vignette is a short introduction to the package for interested readers. In following vignettes describe in detail:  

1) Publicly available data used to develop and test this software.  
[Data](https://kmcconeghy.github.io/flumodelr/articles/02-data.html)  

2) Simple modeling approach: Risk Difference  
[Risk Difference](https://kmcconeghy.github.io/flumodelr/articles/03-ratediff.html)  

3) Explanation of original Serfling Model.  
[Serfling Background](https://kmcconeghy.github.io/flumodelr/articles/04-serfling.html)  

4) Explanation of modern implementation of Serfling Model.  
[Modern Serfling Applications](https://kmcconeghy.github.io/flumodelr/articles/05-modserf.html)  

## Contacting authors  
The primary author of the package was Kevin W. McConeghy. Several other researchers including Andrew Zullo, Rob van Aalst, Vincent Mor, Stefan Gravenstein provided statistical consultation, clinical insight and institutional support.  