---
title: "flumodelr: Introduction"
author: "Kevin W. McConeghy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flumodelr: Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Welcome to flumodelr! This program was written as a companion to academic work performed by researchers at Brown University in collaboration with Sanofi-Pasteur. The primary objective was to streamline and formalize published work on estimating attributable influenza cases. We drew from many sources which are acknowledged and cited throughout in the development of this package. 

## Introduction

This vignette is a short introduction to the package for interested readers. In following vignettes describe in detail:  
1) Publicly available data used to develop and test this software. See: INSERT LINK  
2) Background and context of estimating influenza morbidity. See: INSERT LINK  
3) Programming and set-up of our own functions. See: INSERT LINK  
4) Reproduced example from an unaffiliated published scientific study. See: INSERT LINK  
5) Special models, testing assumptions, and estimate stability analyses. See: INSERT LINK  

## Contacting authors  
The primary author of the package was Kevin W. McConeghy. Several other researchers including Andrew Zullo, Rob Van Aalst, Vincent Mor, Stefan Gravenstein provided statistical consultation, clinical insight and institutional support.  